/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LetsConvert {
  LetsConvert._();

  static const _kFontFam = 'LetsConvert';
  static const _kFontPkg = null;

  static const IconData ic_lets_convert = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
